[tool.pytest.ini_options]
testpaths = [
    "tests"
]
markers = [
    "getters: marks tests as end to end (deselect with '-m \"not getters\"')",
    "create: marks tests as integration (deselect with '-m \"not create\"')",
]
log_cli = true
log_cli_level = "CRITICAL"
log_cli_format = "%(message)s"

log_file = "test_reports/pytest.log"
log_file_level = "INFO"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
